
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FoodService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5920/foodservice/recipes?wsdl")
public class FoodService
    extends Service
{

    private final static URL FOODSERVICE_WSDL_LOCATION;
    private final static WebServiceException FOODSERVICE_EXCEPTION;
    private final static QName FOODSERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "FoodService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5920/foodservice/recipes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FOODSERVICE_WSDL_LOCATION = url;
        FOODSERVICE_EXCEPTION = e;
    }

    public FoodService() {
        super(__getWsdlLocation(), FOODSERVICE_QNAME);
    }

    public FoodService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FOODSERVICE_QNAME, features);
    }

    public FoodService(URL wsdlLocation) {
        super(wsdlLocation, FOODSERVICE_QNAME);
    }

    public FoodService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FOODSERVICE_QNAME, features);
    }

    public FoodService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FoodService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Food
     */
    @WebEndpoint(name = "food")
    public Food getFood() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "food"), Food.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Food
     */
    @WebEndpoint(name = "food")
    public Food getFood(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "food"), Food.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FOODSERVICE_EXCEPTION!= null) {
            throw FOODSERVICE_EXCEPTION;
        }
        return FOODSERVICE_WSDL_LOCATION;
    }

}
