
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CaloriesService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5990/calories/calculator?wsdl")
public class CaloriesService
    extends Service
{

    private final static URL CALORIESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALORIESSERVICE_EXCEPTION;
    private final static QName CALORIESSERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "CaloriesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5990/calories/calculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALORIESSERVICE_WSDL_LOCATION = url;
        CALORIESSERVICE_EXCEPTION = e;
    }

    public CaloriesService() {
        super(__getWsdlLocation(), CALORIESSERVICE_QNAME);
    }

    public CaloriesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALORIESSERVICE_QNAME, features);
    }

    public CaloriesService(URL wsdlLocation) {
        super(wsdlLocation, CALORIESSERVICE_QNAME);
    }

    public CaloriesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALORIESSERVICE_QNAME, features);
    }

    public CaloriesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaloriesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CaloriesCalculator
     */
    @WebEndpoint(name = "Calculator")
    public CaloriesCalculator getCalculator() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "Calculator"), CaloriesCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaloriesCalculator
     */
    @WebEndpoint(name = "Calculator")
    public CaloriesCalculator getCalculator(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "Calculator"), CaloriesCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALORIESSERVICE_EXCEPTION!= null) {
            throw CALORIESSERVICE_EXCEPTION;
        }
        return CALORIESSERVICE_WSDL_LOCATION;
    }

}
