
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActivityHistoryValueService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/activityhistoryvalue?wsdl")
public class ActivityHistoryValueService
    extends Service
{

    private final static URL ACTIVITYHISTORYVALUESERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITYHISTORYVALUESERVICE_EXCEPTION;
    private final static QName ACTIVITYHISTORYVALUESERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "ActivityHistoryValueService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5910/lifestyle/storageservice/activityhistoryvalue?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITYHISTORYVALUESERVICE_WSDL_LOCATION = url;
        ACTIVITYHISTORYVALUESERVICE_EXCEPTION = e;
    }

    public ActivityHistoryValueService() {
        super(__getWsdlLocation(), ACTIVITYHISTORYVALUESERVICE_QNAME);
    }

    public ActivityHistoryValueService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITYHISTORYVALUESERVICE_QNAME, features);
    }

    public ActivityHistoryValueService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITYHISTORYVALUESERVICE_QNAME);
    }

    public ActivityHistoryValueService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITYHISTORYVALUESERVICE_QNAME, features);
    }

    public ActivityHistoryValueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityHistoryValueService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRUDActivityHistoryValue
     */
    @WebEndpoint(name = "CRUD")
    public CRUDActivityHistoryValue getCRUD() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDActivityHistoryValue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRUDActivityHistoryValue
     */
    @WebEndpoint(name = "CRUD")
    public CRUDActivityHistoryValue getCRUD(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDActivityHistoryValue.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITYHISTORYVALUESERVICE_EXCEPTION!= null) {
            throw ACTIVITYHISTORYVALUESERVICE_EXCEPTION;
        }
        return ACTIVITYHISTORYVALUESERVICE_WSDL_LOCATION;
    }

}
