
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActivityValueTypeService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/activityvaluetype?wsdl")
public class ActivityValueTypeService
    extends Service
{

    private final static URL ACTIVITYVALUETYPESERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITYVALUETYPESERVICE_EXCEPTION;
    private final static QName ACTIVITYVALUETYPESERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "ActivityValueTypeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5910/lifestyle/storageservice/activityvaluetype?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITYVALUETYPESERVICE_WSDL_LOCATION = url;
        ACTIVITYVALUETYPESERVICE_EXCEPTION = e;
    }

    public ActivityValueTypeService() {
        super(__getWsdlLocation(), ACTIVITYVALUETYPESERVICE_QNAME);
    }

    public ActivityValueTypeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITYVALUETYPESERVICE_QNAME, features);
    }

    public ActivityValueTypeService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITYVALUETYPESERVICE_QNAME);
    }

    public ActivityValueTypeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITYVALUETYPESERVICE_QNAME, features);
    }

    public ActivityValueTypeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityValueTypeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRUDActivityValueType
     */
    @WebEndpoint(name = "CRUD")
    public CRUDActivityValueType getCRUD() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDActivityValueType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRUDActivityValueType
     */
    @WebEndpoint(name = "CRUD")
    public CRUDActivityValueType getCRUD(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDActivityValueType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITYVALUETYPESERVICE_EXCEPTION!= null) {
            throw ACTIVITYVALUETYPESERVICE_EXCEPTION;
        }
        return ACTIVITYVALUETYPESERVICE_WSDL_LOCATION;
    }

}
