
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ActivityHistoryService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/activityhistory?wsdl")
public class ActivityHistoryService
    extends Service
{

    private final static URL ACTIVITYHISTORYSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACTIVITYHISTORYSERVICE_EXCEPTION;
    private final static QName ACTIVITYHISTORYSERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "ActivityHistoryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5910/lifestyle/storageservice/activityhistory?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACTIVITYHISTORYSERVICE_WSDL_LOCATION = url;
        ACTIVITYHISTORYSERVICE_EXCEPTION = e;
    }

    public ActivityHistoryService() {
        super(__getWsdlLocation(), ACTIVITYHISTORYSERVICE_QNAME);
    }

    public ActivityHistoryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACTIVITYHISTORYSERVICE_QNAME, features);
    }

    public ActivityHistoryService(URL wsdlLocation) {
        super(wsdlLocation, ACTIVITYHISTORYSERVICE_QNAME);
    }

    public ActivityHistoryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACTIVITYHISTORYSERVICE_QNAME, features);
    }

    public ActivityHistoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityHistoryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRUDActivityHistory
     */
    @WebEndpoint(name = "CRUD")
    public CRUDActivityHistory getCRUD() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDActivityHistory.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRUDActivityHistory
     */
    @WebEndpoint(name = "CRUD")
    public CRUDActivityHistory getCRUD(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDActivityHistory.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACTIVITYHISTORYSERVICE_EXCEPTION!= null) {
            throw ACTIVITYHISTORYSERVICE_EXCEPTION;
        }
        return ACTIVITYHISTORYSERVICE_WSDL_LOCATION;
    }

}
