
package it.unitn.sde.finalproject;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "CRUDActivityHistory", targetNamespace = "http://finalproject.sde.unitn.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRUDActivityHistory {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createActivityHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateActivityHistory")
    @ResponseWrapper(localName = "createActivityHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateActivityHistoryResponse")
    public int createActivityHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        ActivityHistory arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.ActivityHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readActivityHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadActivityHistory")
    @ResponseWrapper(localName = "readActivityHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadActivityHistoryResponse")
    public ActivityHistory readActivityHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateActivityHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateActivityHistory")
    @ResponseWrapper(localName = "updateActivityHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateActivityHistoryResponse")
    public int updateActivityHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        ActivityHistory arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteActivityHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteActivityHistory")
    @ResponseWrapper(localName = "deleteActivityHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteActivityHistoryResponse")
    public boolean deleteActivityHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
