
package it.unitn.sde.finalproject;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRUDFavouriteFood", targetNamespace = "http://finalproject.sde.unitn.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRUDFavouriteFood {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createFavouriteFood", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateFavouriteFood")
    @ResponseWrapper(localName = "createFavouriteFoodResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateFavouriteFoodResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/createFavouriteFoodRequest", output = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/createFavouriteFoodResponse")
    public int createFavouriteFood(
        @WebParam(name = "arg0", targetNamespace = "")
        FavouriteFood arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.FavouriteFood
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readFavouriteFood", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadFavouriteFood")
    @ResponseWrapper(localName = "readFavouriteFoodResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadFavouriteFoodResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/readFavouriteFoodRequest", output = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/readFavouriteFoodResponse")
    public FavouriteFood readFavouriteFood(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateFavouriteFood", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateFavouriteFood")
    @ResponseWrapper(localName = "updateFavouriteFoodResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateFavouriteFoodResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/updateFavouriteFoodRequest", output = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/updateFavouriteFoodResponse")
    public int updateFavouriteFood(
        @WebParam(name = "arg0", targetNamespace = "")
        FavouriteFood arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteFavouriteFood", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteFavouriteFood")
    @ResponseWrapper(localName = "deleteFavouriteFoodResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteFavouriteFoodResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/deleteFavouriteFoodRequest", output = "http://finalproject.sde.unitn.it/CRUDFavouriteFood/deleteFavouriteFoodResponse")
    public boolean deleteFavouriteFood(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
