
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExerciseCategoryService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/exercisecategory?wsdl")
public class ExerciseCategoryService
    extends Service
{

    private final static URL EXERCISECATEGORYSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXERCISECATEGORYSERVICE_EXCEPTION;
    private final static QName EXERCISECATEGORYSERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "ExerciseCategoryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5910/lifestyle/storageservice/exercisecategory?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXERCISECATEGORYSERVICE_WSDL_LOCATION = url;
        EXERCISECATEGORYSERVICE_EXCEPTION = e;
    }

    public ExerciseCategoryService() {
        super(__getWsdlLocation(), EXERCISECATEGORYSERVICE_QNAME);
    }

    public ExerciseCategoryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXERCISECATEGORYSERVICE_QNAME, features);
    }

    public ExerciseCategoryService(URL wsdlLocation) {
        super(wsdlLocation, EXERCISECATEGORYSERVICE_QNAME);
    }

    public ExerciseCategoryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXERCISECATEGORYSERVICE_QNAME, features);
    }

    public ExerciseCategoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExerciseCategoryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRUDExerciseCategory
     */
    @WebEndpoint(name = "CRUD")
    public CRUDExerciseCategory getCRUD() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDExerciseCategory.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRUDExerciseCategory
     */
    @WebEndpoint(name = "CRUD")
    public CRUDExerciseCategory getCRUD(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDExerciseCategory.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXERCISECATEGORYSERVICE_EXCEPTION!= null) {
            throw EXERCISECATEGORYSERVICE_EXCEPTION;
        }
        return EXERCISECATEGORYSERVICE_WSDL_LOCATION;
    }

}
