
package it.unitn.sde.finalproject;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRUDExerciseHistory", targetNamespace = "http://finalproject.sde.unitn.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRUDExerciseHistory {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createExerciseHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateExerciseHistory")
    @ResponseWrapper(localName = "createExerciseHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateExerciseHistoryResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/createExerciseHistoryRequest", output = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/createExerciseHistoryResponse")
    public int createExerciseHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        ExerciseHistory arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.ExerciseHistory
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readExerciseHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadExerciseHistory")
    @ResponseWrapper(localName = "readExerciseHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadExerciseHistoryResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/readExerciseHistoryRequest", output = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/readExerciseHistoryResponse")
    public ExerciseHistory readExerciseHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateExerciseHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateExerciseHistory")
    @ResponseWrapper(localName = "updateExerciseHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateExerciseHistoryResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/updateExerciseHistoryRequest", output = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/updateExerciseHistoryResponse")
    public int updateExerciseHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        ExerciseHistory arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteExerciseHistory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteExerciseHistory")
    @ResponseWrapper(localName = "deleteExerciseHistoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteExerciseHistoryResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/deleteExerciseHistoryRequest", output = "http://finalproject.sde.unitn.it/CRUDExerciseHistory/deleteExerciseHistoryResponse")
    public boolean deleteExerciseHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
