
package it.unitn.sde.finalproject;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRUDActivity", targetNamespace = "http://finalproject.sde.unitn.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRUDActivity {


    /**
     * 
     * @return
     *     returns java.util.List<it.unitn.sde.finalproject.Activity>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getActivities", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetActivities")
    @ResponseWrapper(localName = "getActivitiesResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetActivitiesResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDActivity/getActivitiesRequest", output = "http://finalproject.sde.unitn.it/CRUDActivity/getActivitiesResponse")
    public List<Activity> getActivities();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createActivity", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateActivity")
    @ResponseWrapper(localName = "createActivityResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateActivityResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDActivity/createActivityRequest", output = "http://finalproject.sde.unitn.it/CRUDActivity/createActivityResponse")
    public int createActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        Activity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.Activity
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readActivity", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadActivity")
    @ResponseWrapper(localName = "readActivityResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadActivityResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDActivity/readActivityRequest", output = "http://finalproject.sde.unitn.it/CRUDActivity/readActivityResponse")
    public Activity readActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateActivity", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateActivity")
    @ResponseWrapper(localName = "updateActivityResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateActivityResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDActivity/updateActivityRequest", output = "http://finalproject.sde.unitn.it/CRUDActivity/updateActivityResponse")
    public int updateActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        Activity arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteActivity", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteActivity")
    @ResponseWrapper(localName = "deleteActivityResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteActivityResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDActivity/deleteActivityRequest", output = "http://finalproject.sde.unitn.it/CRUDActivity/deleteActivityResponse")
    public boolean deleteActivity(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "linkExerciseCategory", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.LinkExerciseCategory")
    @ResponseWrapper(localName = "linkExerciseCategoryResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.LinkExerciseCategoryResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDActivity/linkExerciseCategoryRequest", output = "http://finalproject.sde.unitn.it/CRUDActivity/linkExerciseCategoryResponse")
    public void linkExerciseCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
