
package it.unitn.sde.finalproject;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CRUDHealthProfile", targetNamespace = "http://finalproject.sde.unitn.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CRUDHealthProfile {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createHealthProfile", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateHealthProfile")
    @ResponseWrapper(localName = "createHealthProfileResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CreateHealthProfileResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDHealthProfile/createHealthProfileRequest", output = "http://finalproject.sde.unitn.it/CRUDHealthProfile/createHealthProfileResponse")
    public int createHealthProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        HealthProfile arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.HealthProfile
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readHealthProfile", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadHealthProfile")
    @ResponseWrapper(localName = "readHealthProfileResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.ReadHealthProfileResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDHealthProfile/readHealthProfileRequest", output = "http://finalproject.sde.unitn.it/CRUDHealthProfile/readHealthProfileResponse")
    public HealthProfile readHealthProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateHealthProfile", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateHealthProfile")
    @ResponseWrapper(localName = "updateHealthProfileResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.UpdateHealthProfileResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDHealthProfile/updateHealthProfileRequest", output = "http://finalproject.sde.unitn.it/CRUDHealthProfile/updateHealthProfileResponse")
    public int updateHealthProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        HealthProfile arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteHealthProfile", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteHealthProfile")
    @ResponseWrapper(localName = "deleteHealthProfileResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeleteHealthProfileResponse")
    @Action(input = "http://finalproject.sde.unitn.it/CRUDHealthProfile/deleteHealthProfileRequest", output = "http://finalproject.sde.unitn.it/CRUDHealthProfile/deleteHealthProfileResponse")
    public int deleteHealthProfile(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
