
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExerciseService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/exercise?wsdl")
public class ExerciseService
    extends Service
{

    private final static URL EXERCISESERVICE_WSDL_LOCATION;
    private final static WebServiceException EXERCISESERVICE_EXCEPTION;
    private final static QName EXERCISESERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "ExerciseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5910/lifestyle/storageservice/exercise?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXERCISESERVICE_WSDL_LOCATION = url;
        EXERCISESERVICE_EXCEPTION = e;
    }

    public ExerciseService() {
        super(__getWsdlLocation(), EXERCISESERVICE_QNAME);
    }

    public ExerciseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXERCISESERVICE_QNAME, features);
    }

    public ExerciseService(URL wsdlLocation) {
        super(wsdlLocation, EXERCISESERVICE_QNAME);
    }

    public ExerciseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXERCISESERVICE_QNAME, features);
    }

    public ExerciseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExerciseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CRUDExercise
     */
    @WebEndpoint(name = "CRUD")
    public CRUDExercise getCRUD() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDExercise.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CRUDExercise
     */
    @WebEndpoint(name = "CRUD")
    public CRUDExercise getCRUD(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "CRUD"), CRUDExercise.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXERCISESERVICE_EXCEPTION!= null) {
            throw EXERCISESERVICE_EXCEPTION;
        }
        return EXERCISESERVICE_WSDL_LOCATION;
    }

}
