
package it.unitn.sde.finalproject;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Food", targetNamespace = "http://finalproject.sde.unitn.it/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Food {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.Receipt
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipe", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetRecipe")
    @ResponseWrapper(localName = "getRecipeResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetRecipeResponse")
    @Action(input = "http://finalproject.sde.unitn.it/Food/getRecipeRequest", output = "http://finalproject.sde.unitn.it/Food/getRecipeResponse")
    public Receipt getRecipe(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.ReceiptFinder
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecipesByCalories", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetRecipesByCalories")
    @ResponseWrapper(localName = "getRecipesByCaloriesResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetRecipesByCaloriesResponse")
    @Action(input = "http://finalproject.sde.unitn.it/Food/getRecipesByCaloriesRequest", output = "http://finalproject.sde.unitn.it/Food/getRecipesByCaloriesResponse")
    public ReceiptFinder getRecipesByCalories(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns it.unitn.sde.finalproject.EdamamResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculateIngredients", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CalculateIngredients")
    @ResponseWrapper(localName = "calculateIngredientsResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.CalculateIngredientsResponse")
    @Action(input = "http://finalproject.sde.unitn.it/Food/calculateIngredientsRequest", output = "http://finalproject.sde.unitn.it/Food/calculateIngredientsResponse")
    public EdamamResponse calculateIngredients(
        @WebParam(name = "arg0", targetNamespace = "")
        List<String> arg0);

}
