package finalproject.client.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import finalproject.model.ActivityChoosen;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "CRUDActivityChoosen", targetNamespace = "http://finalproject.sde.unitn.it/")
public interface ActivityChoosenWebInterface {

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int createActivityChoosen(
			@WebParam(name = "arg0", targetNamespace = "") ActivityChoosen arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns it.unitn.sde.finalproject.ActivityChoosen
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public ActivityChoosen readActivityChoosen(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int updateActivityChoosen(
			@WebParam(name = "arg0", targetNamespace = "") ActivityChoosen arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public boolean deleteActivityChoosen(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
