package finalproject.client.interfaces;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import finalproject.model.Person;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "CRUDPerson", targetNamespace = "http://finalproject.sde.unitn.it/")
public interface CRUDPerson {

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int createPerson(
			@WebParam(name = "arg0", targetNamespace = "") Person arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns it.unitn.sde.finalproject.Person
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public Person readPerson(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @return returns java.util.List<it.unitn.sde.finalproject.Person>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public List<Person> getPeople();

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<it.unitn.sde.finalproject.Person>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public List<Person> getPeopleByName(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<it.unitn.sde.finalproject.Person>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public List<Person> getPeopleByBirthdate(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<it.unitn.sde.finalproject.Person>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getPeopleByMeasure", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetPeopleByMeasure")
	@ResponseWrapper(localName = "getPeopleByMeasureResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.GetPeopleByMeasureResponse")
	@Action(input = "http://finalproject.sde.unitn.it/CRUDPerson/getPeopleByMeasureRequest", output = "http://finalproject.sde.unitn.it/CRUDPerson/getPeopleByMeasureResponse")
	public List<Person> getPeopleByMeasure(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") String arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int updatePerson(
			@WebParam(name = "arg0", targetNamespace = "") Person arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deletePerson", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeletePerson")
	@ResponseWrapper(localName = "deletePersonResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.DeletePersonResponse")
	@Action(input = "http://finalproject.sde.unitn.it/CRUDPerson/deletePersonRequest", output = "http://finalproject.sde.unitn.it/CRUDPerson/deletePersonResponse")
	public boolean deletePerson(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "linkGoal", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.LinkGoal")
	@ResponseWrapper(localName = "linkGoalResponse", targetNamespace = "http://finalproject.sde.unitn.it/", className = "it.unitn.sde.finalproject.LinkGoalResponse")
	@Action(input = "http://finalproject.sde.unitn.it/CRUDPerson/linkGoalRequest", output = "http://finalproject.sde.unitn.it/CRUDPerson/linkGoalResponse")
	public void linkGoal(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);

}
