package finalproject.client.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import finalproject.model.HealthProfile;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "CRUDHealthProfile", targetNamespace = "http://finalproject.sde.unitn.it/")
public interface CRUDHealthProfile {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int createHealthProfile(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") HealthProfile arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns it.unitn.sde.finalproject.HealthProfile
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public HealthProfile readHealthProfile(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int updateHealthProfile(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") HealthProfile arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public boolean deleteHealthProfile(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
