package finalproject.client.interfaces;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import finalproject.model.Exercise;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "CRUDExercise", targetNamespace = "http://finalproject.sde.unitn.it/")
public interface CRUDExercise {

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int createExercise(
			@WebParam(name = "arg0", targetNamespace = "") Exercise arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns it.unitn.sde.finalproject.Exercise
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public Exercise readExercise(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int updateExercise(
			@WebParam(name = "arg0", targetNamespace = "") Exercise arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public boolean deleteExercise(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
