package finalproject.client.interfaces;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import finalproject.model.ExerciseCategory;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "CRUDExerciseCategory", targetNamespace = "http://finalproject.sde.unitn.it/")
public interface ExerciseCategoryWebInterface {

	/**
	 * 
	 * @return returns
	 *         java.util.List<it.unitn.sde.finalproject.ExerciseCategory>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public List<ExerciseCategory> getCategories();

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int createExerciseCategory(
			@WebParam(name = "arg0", targetNamespace = "") ExerciseCategory arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns it.unitn.sde.finalproject.ExerciseCategory
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public ExerciseCategory readExerciseCategory(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public int updateExerciseCategory(
			@WebParam(name = "arg0", targetNamespace = "") ExerciseCategory arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	public boolean deleteExerciseCategory(
			@WebParam(name = "arg0", targetNamespace = "") int arg0);

}
