
package it.unitn.sde.finalproject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReadRecipesService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5920/food/readrecipes?wsdl")
public class ReadRecipesService
    extends Service
{

    private final static URL READRECIPESSERVICE_WSDL_LOCATION;
    private final static WebServiceException READRECIPESSERVICE_EXCEPTION;
    private final static QName READRECIPESSERVICE_QNAME = new QName("http://finalproject.sde.unitn.it/", "ReadRecipesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5920/food/readrecipes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        READRECIPESSERVICE_WSDL_LOCATION = url;
        READRECIPESSERVICE_EXCEPTION = e;
    }

    public ReadRecipesService() {
        super(__getWsdlLocation(), READRECIPESSERVICE_QNAME);
    }

    public ReadRecipesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), READRECIPESSERVICE_QNAME, features);
    }

    public ReadRecipesService(URL wsdlLocation) {
        super(wsdlLocation, READRECIPESSERVICE_QNAME);
    }

    public ReadRecipesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, READRECIPESSERVICE_QNAME, features);
    }

    public ReadRecipesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReadRecipesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReadRecipes
     */
    @WebEndpoint(name = "ReadRecipes")
    public ReadRecipes getReadRecipes() {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "ReadRecipes"), ReadRecipes.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReadRecipes
     */
    @WebEndpoint(name = "ReadRecipes")
    public ReadRecipes getReadRecipes(WebServiceFeature... features) {
        return super.getPort(new QName("http://finalproject.sde.unitn.it/", "ReadRecipes"), ReadRecipes.class, features);
    }

    private static URL __getWsdlLocation() {
        if (READRECIPESSERVICE_EXCEPTION!= null) {
            throw READRECIPESSERVICE_EXCEPTION;
        }
        return READRECIPESSERVICE_WSDL_LOCATION;
    }

}
