package finalproject.client.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import finalproject.client.interfaces.CRUDExcludedFood;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "ExcludedFoodService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/excludedfood?wsdl")
public class ExcludedFoodService extends Service {

	private final static URL EXCLUDEDFOODSERVICE_WSDL_LOCATION;
	private final static WebServiceException EXCLUDEDFOODSERVICE_EXCEPTION;
	private final static QName EXCLUDEDFOODSERVICE_QNAME = new QName(
			"http://finalproject.sde.unitn.it/", "ExcludedFoodService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(
					"http://localhost:5910/lifestyle/storageservice/excludedfood?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		EXCLUDEDFOODSERVICE_WSDL_LOCATION = url;
		EXCLUDEDFOODSERVICE_EXCEPTION = e;
	}

	public ExcludedFoodService() {
		super(__getWsdlLocation(), EXCLUDEDFOODSERVICE_QNAME);
	}

	public ExcludedFoodService(WebServiceFeature... features) {
		super(__getWsdlLocation(), EXCLUDEDFOODSERVICE_QNAME, features);
	}

	public ExcludedFoodService(URL wsdlLocation) {
		super(wsdlLocation, EXCLUDEDFOODSERVICE_QNAME);
	}

	public ExcludedFoodService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, EXCLUDEDFOODSERVICE_QNAME, features);
	}

	public ExcludedFoodService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ExcludedFoodService(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns CRUDExcludedFood
	 */
	@WebEndpoint(name = "CRUD")
	public CRUDExcludedFood getCRUD() {
		return super.getPort(new QName("http://finalproject.sde.unitn.it/",
				"CRUD"), CRUDExcludedFood.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns CRUDExcludedFood
	 */
	@WebEndpoint(name = "CRUD")
	public CRUDExcludedFood getCRUD(WebServiceFeature... features) {
		return super.getPort(new QName("http://finalproject.sde.unitn.it/",
				"CRUD"), CRUDExcludedFood.class, features);
	}

	private static URL __getWsdlLocation() {
		if (EXCLUDEDFOODSERVICE_EXCEPTION != null) {
			throw EXCLUDEDFOODSERVICE_EXCEPTION;
		}
		return EXCLUDEDFOODSERVICE_WSDL_LOCATION;
	}

}
