package finalproject.client.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import finalproject.client.interfaces.CRUDFavouriteFood;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "FavouriteFoodService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/favouritefood?wsdl")
public class FavouriteFoodService extends Service {

	private final static URL FAVOURITEFOODSERVICE_WSDL_LOCATION;
	private final static WebServiceException FAVOURITEFOODSERVICE_EXCEPTION;
	private final static QName FAVOURITEFOODSERVICE_QNAME = new QName(
			"http://finalproject.sde.unitn.it/", "FavouriteFoodService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(
					"http://localhost:5910/lifestyle/storageservice/favouritefood?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		FAVOURITEFOODSERVICE_WSDL_LOCATION = url;
		FAVOURITEFOODSERVICE_EXCEPTION = e;
	}

	public FavouriteFoodService() {
		super(__getWsdlLocation(), FAVOURITEFOODSERVICE_QNAME);
	}

	public FavouriteFoodService(WebServiceFeature... features) {
		super(__getWsdlLocation(), FAVOURITEFOODSERVICE_QNAME, features);
	}

	public FavouriteFoodService(URL wsdlLocation) {
		super(wsdlLocation, FAVOURITEFOODSERVICE_QNAME);
	}

	public FavouriteFoodService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, FAVOURITEFOODSERVICE_QNAME, features);
	}

	public FavouriteFoodService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public FavouriteFoodService(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns CRUDFavouriteFood
	 */
	@WebEndpoint(name = "CRUD")
	public CRUDFavouriteFood getCRUD() {
		return super.getPort(new QName("http://finalproject.sde.unitn.it/",
				"CRUD"), CRUDFavouriteFood.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns CRUDFavouriteFood
	 */
	@WebEndpoint(name = "CRUD")
	public CRUDFavouriteFood getCRUD(WebServiceFeature... features) {
		return super.getPort(new QName("http://finalproject.sde.unitn.it/",
				"CRUD"), CRUDFavouriteFood.class, features);
	}

	private static URL __getWsdlLocation() {
		if (FAVOURITEFOODSERVICE_EXCEPTION != null) {
			throw FAVOURITEFOODSERVICE_EXCEPTION;
		}
		return FAVOURITEFOODSERVICE_WSDL_LOCATION;
	}

}
