package finalproject.client.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import finalproject.client.interfaces.GoalChoosenWebInterface;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "GoalChoosenService", targetNamespace = "http://finalproject.sde.unitn.it/", wsdlLocation = "http://localhost:5910/lifestyle/storageservice/goalchoosen?wsdl")
public class GoalChoosenService extends Service {

	private final static URL GOALCHOOSENSERVICE_WSDL_LOCATION;
	private final static WebServiceException GOALCHOOSENSERVICE_EXCEPTION;
	private final static QName GOALCHOOSENSERVICE_QNAME = new QName(
			"http://finalproject.sde.unitn.it/", "GoalChoosenService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(
					"http://localhost:5910/lifestyle/storageservice/goalchoosen?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		GOALCHOOSENSERVICE_WSDL_LOCATION = url;
		GOALCHOOSENSERVICE_EXCEPTION = e;
	}

	public GoalChoosenService() {
		super(__getWsdlLocation(), GOALCHOOSENSERVICE_QNAME);
	}

	public GoalChoosenService(WebServiceFeature... features) {
		super(__getWsdlLocation(), GOALCHOOSENSERVICE_QNAME, features);
	}

	public GoalChoosenService(URL wsdlLocation) {
		super(wsdlLocation, GOALCHOOSENSERVICE_QNAME);
	}

	public GoalChoosenService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, GOALCHOOSENSERVICE_QNAME, features);
	}

	public GoalChoosenService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public GoalChoosenService(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns CRUDGoalChoosen
	 */
	@WebEndpoint(name = "CRUD")
	public GoalChoosenWebInterface getCRUD() {
		return super.getPort(new QName("http://finalproject.sde.unitn.it/",
				"CRUD"), GoalChoosenWebInterface.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns CRUDGoalChoosen
	 */
	@WebEndpoint(name = "CRUD")
	public GoalChoosenWebInterface getCRUD(WebServiceFeature... features) {
		return super.getPort(new QName("http://finalproject.sde.unitn.it/",
				"CRUD"), GoalChoosenWebInterface.class, features);
	}

	private static URL __getWsdlLocation() {
		if (GOALCHOOSENSERVICE_EXCEPTION != null) {
			throw GOALCHOOSENSERVICE_EXCEPTION;
		}
		return GOALCHOOSENSERVICE_WSDL_LOCATION;
	}

}
